<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>AlmostServiceBus</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AMQPNetLite" Version="2.5.3" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="AlmostServiceBus.Tests" />
  </ItemGroup>
</Project>
